### ISSUE TITLE
Package installs as 'src'

### ISSUE THREAD

**Issue by jayvdb** [AdamGold/pypkgfreeze#9]
See voodoo I needed to do in https://build.opensuse.org/package/view_file/home:jayvdb:py-new/python-pypkgfreeze/python-pypkgfreeze.spec?expand=1

Also `https://github.com/openSUSE/rpmlint-checks/pull/49`

**Comment by AdamGold** [comment]
Thank you. Should be fixed in `0.1.6`.

**Comment by jayvdb** [comment]
Fixed
